@startuml hello-world

!include ../aws.pu
!includeurl AWSPuml/AWSSimplified.puml

title AWS Icons Hello World

AWSCloudGroup(aws, "AWS Cloud") {
  note as hello
  Hello, AWS Icons!
  end note
}

@enduml

