@startuml AWS

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v20.0/dist
!includeurl AWSPuml/AWSCommon.puml

' Minimal helper used by hello-world.pu
!define AWSCloudGroup(g_alias, g_label="AWS Cloud") rectangle g_label as g_alias

@enduml
